version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build

permissions:
  - object: /
    pattern: "**"
    owner:
    group:

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas:
